
import styles from "@/styles/page.module.scss"
import HeaderSession from "@/src/app/sessions/sessioncompoments/headersession";

const Page = () => {
    return (
        <div className={styles.sessionPage}>
            <div className={styles.sessionContent} >
                <HeaderSession title="Privacy Policy" />
                <div className={styles.mainSetting}>
                    <h2>1. Policy effective date</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>
                    <h2>2. Lorem ipsum dolor sit amet consectetur</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>
                    <h2>3. Lorem ipsum dolor sit amet consectetur</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>
                    <h2>4. Lorem ipsum dolor sit amet consectetur</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>
                    <h2>5. Lorem ipsum dolor sit amet consectetur</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>
                    <h2>6. Lorem ipsum dolor sit amet consectetur</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>
                    <h2>7. Lorem ipsum dolor sit amet consectetur</h2>
                    <p>Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam Lorem ipsum dolor sit amet consectetur. Et neque elementum et enim quis. Augue a aliquet augue viverra risus commodo aliquam. Egestas volutpat nunc non aliquet dolor enim nam auctor cursus. Id cras nam condimentum arcu ullamcorper auctor enim semper. Cursus ut at aliquam adipiscing magna sed vulputate. Tortor velit at amet pharetra pellentesque. Etiam facilisis amet eu sapien sollicitudin. Donec aliquet erat libero non mattis sed dui justo. A tristique et ante nullam ut volutpat sagittis turpis. Est lectus et viverra gravida metus in quam.</p>

                </div>
            </div>
        </div>
    );
};

export default Page;
